#!/bin/sh
START=$PWD
DIRNAME=`dirname "$0"`
SCRIPTS_HOME=`cd "$DIRNAME" > /dev/null && pwd`
CURATOR_BASE=$SCRIPTS_HOME/..
CURATOR_BASE=`cd "$CURATOR_BASE" > /dev/null && pwd`
LIBDIR=$CURATOR_BASE/lib
COMPONENTDIR=$CURATOR_BASE/components
CONFIGDIR=$CURATOR_BASE/configs

VERSION=4.1.1
MODELVERSION=4.0.1

MODEL_JAR=illinoisSRL-nom-models-$MODELVERSION.jar
BIN_JAR=illinoisSRL-$VERSION.jar

COMPONENT_CLASSPATH=$COMPONENTDIR/illinois-nom-srl-server.jar:$CURATOR_BASE:$COMPONENTDIR/illinois-abstract-server.jar:$COMPONENTDIR/curator-interfaces.jar

MODEL_CLASSPATH=$LIBDIR/$MODEL_JAR


LIB_CLASSPATH=$CURATOR_BASE
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/$BIN_JAR
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/commons-cli-1.2.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/IllinoisSL-core-0.1-withJLIS.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/JLIS-multiclass-0.5.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/LBJava-1.0.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/brown-clusters-1.0.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/illinois-common-resources-1.1.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/commons-codec-1.8.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/commons-collections-3.2.1.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/commons-configuration-1.6.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/commons-lang-2.5.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/commons-logging-1.1.1.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/coreUtilities-0.2.5.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/edison-0.7.1.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/gson-2.2.4.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/httpclient-4.1.2.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/httpcore-4.1.3.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/inference-0.4.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/jgrapht-0.8.3.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/jwnl-1.4_rc3.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/libthrift-0.8.0.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/logback-classic-0.9.28.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/logback-core-0.9.28.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/slf4j-api-1.6.1.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/snowball-1.0.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/trove4j-3.0.3.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/verb-nom-data-1.0.jar


CLASSPATH=$COMPONENT_CLASSPATH:$LIB_CLASSPATH:$MODEL_CLASSPATH:$CONFIGDIR

cd $CURATOR_BASE

echo "LIBDIR: $LIBDIR"

CMD="java -cp $CLASSPATH -Dhome=$CURATOR_BASE -Xmx4G edu.illinois.cs.cogcomp.annotation.server.IllinoisNomSRLServer -c $CONFIGDIR/srl-config.properties  $@"


echo $CMD
exec $CMD
cd $START
