#!/bin/sh
START=$PWD
DIRNAME=`dirname "$0"`
SCRIPTS_HOME=`cd "$DIRNAME" > /dev/null && pwd`
CURATOR_BASE=$SCRIPTS_HOME/..
CURATOR_BASE=`cd "$CURATOR_BASE" > /dev/null && pwd`
LIBDIR=$CURATOR_BASE/lib
COMPONENTDIR=$CURATOR_BASE/components

COMPONENT_CLASSPATH=$CURATOR_BASE:$COMPONENTDIR/illinois-coref-ace-server.jar:$COMPONENTDIR/curator-interfaces.jar:$CURATOR_BASE:$COMPONENTDIR/illinois-abstract-server.jar

LIB_CLASSPATH=$LIBDIR/cogcomp-common-resources-1.2.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/commons-cli-1.2.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/commons-codec-1.8.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/commons-lang-2.5.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/commons-logging-1.1.1.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/coref-deps-list.txt
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/coreUtilities-0.1.7.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/curator-interfaces-0.7.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/edison-0.4.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/gson-2.2.4.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/h2-1.3.157.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/httpclient-4.1.2.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/httpcore-4.1.3.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/illinois-coref-ace-model-1.5.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/illinois-coref-ace-resources-1.5.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/illinois-entity-similarity-1.0.0.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/illinois-pos-1.7.1.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/junit-4.1.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/jwnl-1.4_rc3.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/LBJ-2.8.2.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/LBJLibrary-2.8.2.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/LBJCoref-1.5.5-SNAPSHOT.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/libthrift-0.8.0.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/logback-classic-0.9.28.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/logback-core-0.9.28.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/SecondString-1.0.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/slf4j-api-1.6.1.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/snowball-1.0.jar
LIB_CLASSPATH=$LIB_CLASSPATH:$LIBDIR/trove4j-3.0.3.jar

CLASSPATH=$COMPONENT_CLASSPATH:$LIB_CLASSPATH

cd $CURATOR_BASE
CMD="java -cp $CLASSPATH -Dhome=$CURATOR_BASE -Xmx6G edu.illinois.cs.cogcomp.annotation.server.IllinoisCorefAceServer -c configs/corefAce.config $@"

echo "$0: running command '$CMD'..."

exec $CMD
 
cd $START
