CURATOR_HOST=trollope
CURATOR_HOME=/shared/$CURATOR_HOST/curator
SCRIPT_HOME=$CURATOR_HOME/scripts
LOG_HOME=$CURATOR_HOME/log
RUN_SCRIPT=runIt.pl
CURATOR_START_DIR=$CURATOR_HOME/dist

source $CURATOR_HOME/setEnvVars.sh